with source as (
    select *
    from {{ source('warehouse_raw', 'suumo_parser_records') }}
)

select
    task_id,
    batch_id,
    source_id,
    data_hash,
    loaded_at,
    nullif(record ->> 'image_public_url', '') as image_public_url,
    nullif(record ->> 'image_storage_path', '') as image_storage_path,
    nullif(record ->> '家賃', '') as rent_price_text,
    nullif(record ->> '敷金', '') as deposit_text,
    nullif(record ->> '管理費_共益費', '') as management_fee_text,
    nullif(record ->> '礼金', '') as key_money_text,
    nullif(record ->> '保証金', '') as guarantee_deposit_text,
    nullif(record ->> '敷引_償却', '') as depreciation_text,
    nullif(record ->> '電話番号', '') as phone_number,
    nullif(record ->> '所在地', '') as address,
    nullif(record ->> '駅徒歩', '') as station_access,
    nullif(record ->> '間取り', '') as layout,
    nullif(record ->> '専有面積', '') as exclusive_area_text,
    nullif(record ->> '築年数', '') as building_age_text,
    nullif(record ->> '階', '') as floor_text,
    nullif(record ->> '向き', '') as direction,
    nullif(record ->> '建物種別', '') as building_type,
    nullif(record ->> '間取り詳細', '') as layout_detail,
    nullif(record ->> '構造', '') as structure,
    nullif(record ->> '階建', '') as building_floors,
    nullif(record ->> '築年月', '') as built_at_text,
    nullif(record ->> 'エネルギー消費性能', '') as energy_efficiency,
    nullif(record ->> '断熱性能', '') as insulation_performance,
    nullif(record ->> '目安光熱費', '') as estimated_utility_cost,
    nullif(record ->> '損保', '') as insurance,
    nullif(record ->> '駐車場', '') as parking,
    nullif(record ->> '入居', '') as move_in,
    nullif(record ->> '条件', '') as conditions,
    nullif(record ->> 'SUUMO物件コード', '') as suumo_property_code,
    nullif(record ->> '情報更新日', '') as information_updated_at_text,
    nullif(record ->> '契約期間', '') as contract_period,
    nullif(record ->> '仲介手数料', '') as brokerage_fee,
    nullif(record ->> '保証会社', '') as guarantee_company,
    nullif(record ->> 'ほか初期費用', '') as other_initial_costs,
    nullif(record ->> 'ほか諸費用', '') as other_monthly_costs,
    nullif(record ->> '取引態様', '') as transaction_type,
    nullif(record ->> '取り扱い店舗物件コード', '') as shop_property_code,
    nullif(record ->> '総戸数', '') as total_units,
    nullif(record ->> '次回更新予定日', '') as next_update_date_text,
    nullif(record ->> '備考', '') as remarks
from source
